# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CalibrationCurve',
                'doc_host': 'https://Rhys-McAlister.github.io',
                'git_url': 'https://github.com/Rhys-McAlister/CalibrationCurve',
                'lib_path': 'CalibrationCurve'},
  'syms': {'CalibrationCurve.core': {'CalibrationCurve.core.foo': ('core.html#foo', 'CalibrationCurve/core.py')}}}
